name: incode_test_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  json_serializable: ^6.9.0
  daily_extensions: ^1.2.0
  flutter_svg: ^2.0.17
  go_router: ^14.7.1
  realm: ^20.0.1
  objectid: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.14
  flutter_gen_runner: 5.8.0

flutter_gen:
  output: lib/resources/gen
  lineLength: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

